branch-defaults:
  default:
    environment: ruby-cf-sample-app-dev
    group_suffix: null
global:
  application_name: ruby-cf-sample-app
  default_ec2_keyname: pcf-keypair
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: null
